//! The actual GOLD uplink (UM) / downlink (DM) element table.
//!
//! Two sources, chained together by [`crate::elements::um_table`]/
//! [`crate::elements::dm_table`]:
//!
//! - `HOPPIE_UM_TABLE`/`HOPPIE_DM_TABLE`: a handful of Hoppie-network-
//!   specific rows with no GOLD equivalent — the network's simplified
//!   plain-text logon handshake (real ATN/FANS CPDLC logon is a binary
//!   application-layer handshake, not a text message).
//! - `GOLD_UM_TABLE`/`GOLD_DM_TABLE`: the real ICAO GOLD message-
//!   element catalog (198 UM + 89 DM = 287 rows), DATA-transcribed from
//!   `skiselkov/libcpdlc`'s `cpdlc_msg_infos[]` (`src/cpdlc_infos.c`,
//!   MIT, C) via a one-off Python extraction script — not hand-typed,
//!   and not copying libcpdlc's code (which is ASN.1/offsetof-based C
//!   struct wiring irrelevant here). Each row's `id` is the real GOLD
//!   element number (e.g. `"UM74"`, `"DM67b"`); `template`/
//!   `placeholders`/`response` are transcribed from libcpdlc's
//!   `.text`/`.args`/`.resp` fields.
//!
//! ## Five template patches
//!
//! libcpdlc's own `.text` field is a human-readable display string
//! and, for five elements, is genuinely missing a trailing placeholder
//! that its `.args` array (the structural field) declares — e.g. UM63
//! declares 4 args (time, position, altitude, speed) but its `.text`
//! only shows three `[...]` markers. Left as-is, `resolve()` would
//! silently drop the extra value instead of erroring, since it only
//! checks placeholder *count*, not how many actually appear in the
//! template. Five templates (`UM63`, `UM91`, `DM16`, `DM17`, `DM27`)
//! are therefore patched to include the missing `@N`, phrased to match
//! the closest structurally-identical sibling element in the same
//! table (documented at each patched entry below) — not a guess out of
//! nowhere, but not verbatim libcpdlc text either.
//!
//! Every `ElementSpec` is `'static` data — zero per-element match arms,
//! see `elements.rs`'s module docs for why.

use crate::cpdlc::ResponseRequirement;
use crate::elements::{Direction, ElementSpec, PlaceholderKind};

pub const HOPPIE_UM_TABLE: &[ElementSpec] = &[ElementSpec {
    id: "UM_LOGON_ACCEPTED",
    direction: Direction::Uplink,
    template: "LOGON ACCEPTED",
    placeholders: &[],
    response: ResponseRequirement::NoResponseExpected,
}];

pub const HOPPIE_DM_TABLE: &[ElementSpec] = &[
    ElementSpec {
        id: "DM_REQUEST_LOGON",
        direction: Direction::Downlink,
        template: "REQUEST LOGON",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    // Ends the CPDLC session with the current facility. Sent on
    // disconnect and on app shutdown — leaving a session open means the
    // controller still shows the aircraft as connected, and messages
    // keep queueing server-side until they all land at once on the next
    // start. Wire form per the reference clients: `/data2/{MIN}//N/LOGOFF`.
    ElementSpec {
        id: "DM_LOGOFF",
        direction: Direction::Downlink,
        template: "LOGOFF",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
];

pub const GOLD_UM_TABLE: &[ElementSpec] = &[
    ElementSpec {
        id: "UM0",
        direction: Direction::Uplink,
        template: "UNABLE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM1",
        direction: Direction::Uplink,
        template: "STANDBY",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM2",
        direction: Direction::Uplink,
        template: "REQUEST DEFERRED",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM3",
        direction: Direction::Uplink,
        template: "ROGER",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM4",
        direction: Direction::Uplink,
        template: "AFFIRM",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM5",
        direction: Direction::Uplink,
        template: "NEGATIVE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM6",
        direction: Direction::Uplink,
        template: "EXPECT @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM7",
        direction: Direction::Uplink,
        template: "EXPECT CLIMB AT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM8",
        direction: Direction::Uplink,
        template: "EXPECT CLIMB AT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM9",
        direction: Direction::Uplink,
        template: "EXPECT DESCENT AT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM10",
        direction: Direction::Uplink,
        template: "EXPECT DESCENT AT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM11",
        direction: Direction::Uplink,
        template: "EXPECT CRUISE CLIMB AT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM12",
        direction: Direction::Uplink,
        template: "EXPECT CRUISE CLIMB AT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM13",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT CLIMB TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM14",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT CLIMB TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM15",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT DESCENT TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM16",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT DESCENT TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM17",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT CRUISE CLIMB TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM18",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT CRUISE CLIMB TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM19",
        direction: Direction::Uplink,
        template: "MAINTAIN @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM20",
        direction: Direction::Uplink,
        template: "CLIMB TO AND MAINTAIN @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM21",
        direction: Direction::Uplink,
        template: "AT @1 CLIMB TO AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM22",
        direction: Direction::Uplink,
        template: "AT @1 CLIMB TO AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM23",
        direction: Direction::Uplink,
        template: "DESCEND TO AND MAINTAIN @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM24",
        direction: Direction::Uplink,
        template: "AT @1 DESCEND TO AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM25",
        direction: Direction::Uplink,
        template: "AT @1 DESCEND TO AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM26",
        direction: Direction::Uplink,
        template: "CLIMB TO REACH @1 BY @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM27",
        direction: Direction::Uplink,
        template: "CLIMB TO REACH @1 BY @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM28",
        direction: Direction::Uplink,
        template: "DESCEND TO REACH @1 BY @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM29",
        direction: Direction::Uplink,
        template: "DESCEND TO REACH @1 BY @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM30",
        direction: Direction::Uplink,
        template: "MAINTAIN BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM31",
        direction: Direction::Uplink,
        template: "CLIMB TO AND MAINTAIN BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM32",
        direction: Direction::Uplink,
        template: "DESCEND TO AND MAINTAIN BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM33",
        direction: Direction::Uplink,
        template: "CRUISE @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM34",
        direction: Direction::Uplink,
        template: "CRUISE CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM35",
        direction: Direction::Uplink,
        template: "CRUISE CLIMB ABOVE @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM36",
        direction: Direction::Uplink,
        template: "EXPEDITE CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM37",
        direction: Direction::Uplink,
        template: "EXPEDITE DESCEND TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM38",
        direction: Direction::Uplink,
        template: "IMMEDIATELY CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM39",
        direction: Direction::Uplink,
        template: "IMMEDIATELY DESCEND TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM40",
        direction: Direction::Uplink,
        template: "IMMEDIATELY STOP CLIMB AT @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM41",
        direction: Direction::Uplink,
        template: "IMMEDIATELY STOP DESCENT AT @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM42",
        direction: Direction::Uplink,
        template: "EXPECT TO CROSS @1 AT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM43",
        direction: Direction::Uplink,
        template: "EXPECT TO CROSS @1 AT @2 OR ABOVE",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM44",
        direction: Direction::Uplink,
        template: "EXPECT TO CROSS @1 AT @2 OR BELOW",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM45",
        direction: Direction::Uplink,
        template: "EXPECT TO CROSS @1 AT AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM46",
        direction: Direction::Uplink,
        template: "CROSS @1 AT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM47",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR ABOVE @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM48",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR BELOW @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM49",
        direction: Direction::Uplink,
        template: "CROSS @1 AT AND MAINTAIN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM50",
        direction: Direction::Uplink,
        template: "CROSS @1 BETWEEN @2 AND @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Altitude,
            PlaceholderKind::Altitude,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM51",
        direction: Direction::Uplink,
        template: "CROSS @1 AT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM52",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR BEFORE @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM53",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR AFTER @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM54",
        direction: Direction::Uplink,
        template: "CROSS @1 BETWEEN @2 AND @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Time,
            PlaceholderKind::Time,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM55",
        direction: Direction::Uplink,
        template: "CROSS @1 AT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM56",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR LESS THAN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM57",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR GREATER THAN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM58",
        direction: Direction::Uplink,
        template: "CROSS @1 AT @2 AT @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Time,
            PlaceholderKind::Altitude,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM59",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR BEFORE @2 AT @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Time,
            PlaceholderKind::Altitude,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM60",
        direction: Direction::Uplink,
        template: "CROSS @1 AT OR AFTER @2 AT @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Time,
            PlaceholderKind::Altitude,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM61",
        direction: Direction::Uplink,
        template: "CROSS @1 AT AND MAINTAIN @2 AT @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Altitude,
            PlaceholderKind::Speed,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM62",
        direction: Direction::Uplink,
        template: "AT @1 CROSS @2 AT AND MAINTAIN @3",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::Position,
            PlaceholderKind::Altitude,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    // Patched: libcpdlc's .text lacked the 4th (speed) placeholder its .args declares; phrasing mirrors sibling UM61.
    ElementSpec {
        id: "UM63",
        direction: Direction::Uplink,
        template: "AT @1 CROSS @2 AT AND MAINTAIN @3 AT @4",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::Position,
            PlaceholderKind::Altitude,
            PlaceholderKind::Speed,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM64",
        direction: Direction::Uplink,
        template: "OFFSET @1 @2 OF ROUTE",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM65",
        direction: Direction::Uplink,
        template: "AT @1 OFFSET @2 @3 OF ROUTE",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM66",
        direction: Direction::Uplink,
        template: "AT @1 OFFSET @2 @3 OF ROUTE",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM67",
        direction: Direction::Uplink,
        template: "PROCEED BACK ON ROUTE",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM68",
        direction: Direction::Uplink,
        template: "REJOIN ROUTE BY @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM69",
        direction: Direction::Uplink,
        template: "REJOIN ROUTE BY @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM70",
        direction: Direction::Uplink,
        template: "EXPECT BACK ON ROUTE BY @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM71",
        direction: Direction::Uplink,
        template: "EXPECT BACK ON ROUTE BY @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM72",
        direction: Direction::Uplink,
        template: "RESUME OWN NAVIGATION",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM73",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::PdcData],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM74",
        direction: Direction::Uplink,
        template: "PROCEED DIRECT TO @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM75",
        direction: Direction::Uplink,
        template: "WHEN ABLE PROCEED DIRECT TO @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM76",
        direction: Direction::Uplink,
        template: "AT @1 PROCEED DIRECT TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM77",
        direction: Direction::Uplink,
        template: "AT @1 PROCEED DIRECT TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM78",
        direction: Direction::Uplink,
        template: "AT @1 PROCEED DIRECT TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM79",
        direction: Direction::Uplink,
        template: "CLEARED TO @1 VIA @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Route],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM80",
        direction: Direction::Uplink,
        template: "CLEARED @1",
        placeholders: &[PlaceholderKind::Route],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM81",
        direction: Direction::Uplink,
        template: "CLEARED @1",
        placeholders: &[PlaceholderKind::Procedure],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM82",
        direction: Direction::Uplink,
        template: "CLEARED TO DEVIATE UP TO @1 @2",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM83",
        direction: Direction::Uplink,
        template: "AT @1 CLEARED @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Route],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM84",
        direction: Direction::Uplink,
        template: "AT @1 CLEARED @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Procedure],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM85",
        direction: Direction::Uplink,
        template: "EXPECT @1",
        placeholders: &[PlaceholderKind::Route],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM86",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Route],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM87",
        direction: Direction::Uplink,
        template: "EXPECT DIRECT TO @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM88",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT DIRECT TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM89",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT DIRECT TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM90",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT DIRECT TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    // Patched: libcpdlc's .text lacked 3 trailing placeholders its .args declares; standard holding-pattern phrasing.
    ElementSpec {
        id: "UM91",
        direction: Direction::Uplink,
        template: "HOLD AT @1 MAINTAIN @2 INBOUND TRACK @3 @4 TURN @5 LEG",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Altitude,
            PlaceholderKind::Degrees,
            PlaceholderKind::LateralDirection,
            PlaceholderKind::LegType,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM92",
        direction: Direction::Uplink,
        template: "HOLD AT @1 AS PUBLISHED MAINTAIN @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM93",
        direction: Direction::Uplink,
        template: "EXPECT FURTHER CLEARANCE AT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM94",
        direction: Direction::Uplink,
        template: "TURN @1 HEADING @2",
        placeholders: &[PlaceholderKind::LateralDirection, PlaceholderKind::Degrees],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM95",
        direction: Direction::Uplink,
        template: "TURN @1 GROUND TRACK @2",
        placeholders: &[PlaceholderKind::LateralDirection, PlaceholderKind::Degrees],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM96",
        direction: Direction::Uplink,
        template: "FLY PRESENT HEADING",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM97",
        direction: Direction::Uplink,
        template: "AT @1 FLY HEADING @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Degrees],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM98",
        direction: Direction::Uplink,
        template: "IMMEDIATELY TURN @1 HEADING @2",
        placeholders: &[PlaceholderKind::LateralDirection, PlaceholderKind::Degrees],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM99",
        direction: Direction::Uplink,
        template: "EXPECT @1",
        placeholders: &[PlaceholderKind::Procedure],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM100",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Speed],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM101",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Speed],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM102",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Speed],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM103",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2 TO @3",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::Speed,
            PlaceholderKind::Speed,
        ],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM104",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2 TO @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::Speed,
            PlaceholderKind::Speed,
        ],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM105",
        direction: Direction::Uplink,
        template: "AT @1 EXPECT @2 TO @3",
        placeholders: &[
            PlaceholderKind::Altitude,
            PlaceholderKind::Speed,
            PlaceholderKind::Speed,
        ],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM106",
        direction: Direction::Uplink,
        template: "MAINTAIN @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM107",
        direction: Direction::Uplink,
        template: "MAINTAIN PRESENT SPEED",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM108",
        direction: Direction::Uplink,
        template: "MAINTAIN @1 OR GREATER",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM109",
        direction: Direction::Uplink,
        template: "MAINTAIN @1 OR LESS",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM110",
        direction: Direction::Uplink,
        template: "MAINTAIN @1 TO @2",
        placeholders: &[PlaceholderKind::Speed, PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM111",
        direction: Direction::Uplink,
        template: "INCREASE SPEED TO @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM112",
        direction: Direction::Uplink,
        template: "INCREASE SPEED TO @1 OR GREATER",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM113",
        direction: Direction::Uplink,
        template: "REDUCE SPEED TO @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM114",
        direction: Direction::Uplink,
        template: "REDUCE SPEED TO @1 OR LESS",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM115",
        direction: Direction::Uplink,
        template: "DO NOT EXCEED @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM116",
        direction: Direction::Uplink,
        template: "RESUME NORMAL SPEED",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM117",
        direction: Direction::Uplink,
        template: "CONTACT @1 @2",
        placeholders: &[PlaceholderKind::IcaoName, PlaceholderKind::Frequency],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM118",
        direction: Direction::Uplink,
        template: "AT @1 CONTACT @2 @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::IcaoName,
            PlaceholderKind::Frequency,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM119",
        direction: Direction::Uplink,
        template: "AT @1 CONTACT @2 @3",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::IcaoName,
            PlaceholderKind::Frequency,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM120",
        direction: Direction::Uplink,
        template: "MONITOR @1 @2",
        placeholders: &[PlaceholderKind::IcaoName, PlaceholderKind::Frequency],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM121",
        direction: Direction::Uplink,
        template: "AT @1 MONITOR @2 @3",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::IcaoName,
            PlaceholderKind::Frequency,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM122",
        direction: Direction::Uplink,
        template: "AT @1 CONTACT @2 @3",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::IcaoName,
            PlaceholderKind::Frequency,
        ],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM123",
        direction: Direction::Uplink,
        template: "SQUAWK @1",
        placeholders: &[PlaceholderKind::Squawk],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM124",
        direction: Direction::Uplink,
        template: "STOP SQUAWK",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM125",
        direction: Direction::Uplink,
        template: "SQUAWK ALTITUDE",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM126",
        direction: Direction::Uplink,
        template: "STOP ALTITUDE SQUAWK",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM127",
        direction: Direction::Uplink,
        template: "REPORT BACK ON ROUTE",
        placeholders: &[],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM128",
        direction: Direction::Uplink,
        template: "REPORT LEAVING @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM129",
        direction: Direction::Uplink,
        template: "REPORT LEVEL @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM130",
        direction: Direction::Uplink,
        template: "REPORT PASSING @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM131",
        direction: Direction::Uplink,
        template: "REPORT REMAINING FUEL AND SOULS ON BOARD",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM132",
        direction: Direction::Uplink,
        template: "CONFIRM POSITION",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM133",
        direction: Direction::Uplink,
        template: "CONFIRM ALTITUDE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM134",
        direction: Direction::Uplink,
        template: "CONFIRM SPEED",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM135",
        direction: Direction::Uplink,
        template: "CONFIRM ASSIGNED ALTITUDE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM136",
        direction: Direction::Uplink,
        template: "CONFIRM ASSIGNED SPEED",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM137",
        direction: Direction::Uplink,
        template: "CONFIRM ASSIGNED ROUTE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM138",
        direction: Direction::Uplink,
        template: "CONFIRM TIME OVER REPORTED WAYPOINT",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM139",
        direction: Direction::Uplink,
        template: "CONFIRM REPORTED WAYPOINT",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM140",
        direction: Direction::Uplink,
        template: "CONFIRM NEXT WAYPOINT",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM141",
        direction: Direction::Uplink,
        template: "CONFIRM NEXT WAYPOINT ETA",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM142",
        direction: Direction::Uplink,
        template: "CONFIRM ENSUING WAYPOINT",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM143",
        direction: Direction::Uplink,
        template: "CONFIRM REQUEST",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM144",
        direction: Direction::Uplink,
        template: "CONFIRM SQUAWK",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM145",
        direction: Direction::Uplink,
        template: "CONFIRM HEADING",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM146",
        direction: Direction::Uplink,
        template: "CONFIRM GROUND TRACK",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM147",
        direction: Direction::Uplink,
        template: "REQUEST POSITION REPORT",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM148",
        direction: Direction::Uplink,
        template: "WHEN CAN YOU ACCEPT @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM149",
        direction: Direction::Uplink,
        template: "CAN YOU ACCEPT @1 AT @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Position],
        response: ResponseRequirement::AffirmNegative,
    },
    ElementSpec {
        id: "UM150",
        direction: Direction::Uplink,
        template: "CAN YOU ACCEPT @1 AT @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Time],
        response: ResponseRequirement::AffirmNegative,
    },
    ElementSpec {
        id: "UM151",
        direction: Direction::Uplink,
        template: "WHEN CAN YOU ACCEPT @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM152",
        direction: Direction::Uplink,
        template: "WHEN CAN YOU ACCEPT @1 @2 OFFSET",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM153",
        direction: Direction::Uplink,
        template: "ALTIMETER @1",
        placeholders: &[PlaceholderKind::AltimeterSetting],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM154",
        direction: Direction::Uplink,
        template: "RADAR SERVICES TERMINATED",
        placeholders: &[],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM155",
        direction: Direction::Uplink,
        template: "RADAR CONTACT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM156",
        direction: Direction::Uplink,
        template: "RADAR CONTACT LOST",
        placeholders: &[],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM157",
        direction: Direction::Uplink,
        template: "CHECK STUCK MICROPHONE @1",
        placeholders: &[PlaceholderKind::Frequency],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM158",
        direction: Direction::Uplink,
        template: "ATIS @1",
        placeholders: &[PlaceholderKind::AtisCode],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM159",
        direction: Direction::Uplink,
        template: "ERROR @1",
        placeholders: &[PlaceholderKind::ErrorInfo],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM160",
        direction: Direction::Uplink,
        template: "NEXT DATA AUTHORITY @1",
        placeholders: &[PlaceholderKind::IcaoId],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM161",
        direction: Direction::Uplink,
        template: "END SERVICE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM162",
        direction: Direction::Uplink,
        template: "SERVICE UNAVAILABLE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM163",
        direction: Direction::Uplink,
        template: "@1 @2",
        placeholders: &[PlaceholderKind::IcaoId, PlaceholderKind::Tp4Table],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM164",
        direction: Direction::Uplink,
        template: "WHEN READY",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM165",
        direction: Direction::Uplink,
        template: "THEN",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM166",
        direction: Direction::Uplink,
        template: "DUE TO TRAFFIC",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM167",
        direction: Direction::Uplink,
        template: "DUE TO AIRSPACE RESTRICTION",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM168",
        direction: Direction::Uplink,
        template: "DISREGARD",
        placeholders: &[],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM169",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM170",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM171",
        direction: Direction::Uplink,
        template: "CLIMB AT @1 MINIMUM",
        placeholders: &[PlaceholderKind::VerticalRate],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM172",
        direction: Direction::Uplink,
        template: "CLIMB AT @1 MAXIMUM",
        placeholders: &[PlaceholderKind::VerticalRate],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM173",
        direction: Direction::Uplink,
        template: "DESCEND AT @1 MINIMUM",
        placeholders: &[PlaceholderKind::VerticalRate],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM174",
        direction: Direction::Uplink,
        template: "DESCEND AT @1 MAXIMUM",
        placeholders: &[PlaceholderKind::VerticalRate],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM175",
        direction: Direction::Uplink,
        template: "REPORT REACHING @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM176",
        direction: Direction::Uplink,
        template: "MAINTAIN OWN SEPARATION AND VMC",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM177",
        direction: Direction::Uplink,
        template: "AT PILOTS DISCRETION",
        placeholders: &[],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM179",
        direction: Direction::Uplink,
        template: "SQUAWK IDENT",
        placeholders: &[],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM180",
        direction: Direction::Uplink,
        template: "REPORT REACHING BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM181",
        direction: Direction::Uplink,
        template: "REPORT DISTANCE @1 @2",
        placeholders: &[PlaceholderKind::ToFrom, PlaceholderKind::Position],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM182",
        direction: Direction::Uplink,
        template: "CONFIRM ATIS CODE",
        placeholders: &[],
        response: ResponseRequirement::NoResponseExpected,
    },
    ElementSpec {
        id: "UM183",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "UM187",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "UM194",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "UM195",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM196",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM197",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM198",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::WilcoUnable,
    },
    ElementSpec {
        id: "UM199",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "UM201",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "UM202",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "UM203",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::Roger,
    },
    ElementSpec {
        id: "UM204",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "UM205",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::AffirmNegative,
    },
    ElementSpec {
        id: "UM206",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "UM207",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "UM208",
        direction: Direction::Uplink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
];
pub const GOLD_DM_TABLE: &[ElementSpec] = &[
    ElementSpec {
        id: "DM0",
        direction: Direction::Downlink,
        template: "WILCO",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM1",
        direction: Direction::Downlink,
        template: "UNABLE",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM2",
        direction: Direction::Downlink,
        template: "STANDBY",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM3",
        direction: Direction::Downlink,
        template: "ROGER",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM4",
        direction: Direction::Downlink,
        template: "AFFIRM",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM5",
        direction: Direction::Downlink,
        template: "NEGATIVE",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM6",
        direction: Direction::Downlink,
        template: "REQUEST @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM7",
        direction: Direction::Downlink,
        template: "REQUEST BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM8",
        direction: Direction::Downlink,
        template: "REQUEST CRUISE CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM9",
        direction: Direction::Downlink,
        template: "REQUEST CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM10",
        direction: Direction::Downlink,
        template: "REQUEST DESCENT TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM11",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST CLIMB TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM12",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST DESCENT TO @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM13",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST CLIMB TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM14",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST DESCENT TO @2",
        placeholders: &[PlaceholderKind::Time, PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM15",
        direction: Direction::Downlink,
        template: "REQUEST OFFSET @1 @2 OF ROUTE",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::AnyRequired,
    },
    // Patched: libcpdlc's .text lacked the trailing direction placeholder; phrasing mirrors sibling UM64.
    ElementSpec {
        id: "DM16",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST OFFSET @2 @3 OF ROUTE",
        placeholders: &[
            PlaceholderKind::Position,
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::AnyRequired,
    },
    // Patched: libcpdlc's .text lacked the trailing direction placeholder; phrasing mirrors sibling UM64.
    ElementSpec {
        id: "DM17",
        direction: Direction::Downlink,
        template: "AT @1 REQUEST OFFSET @2 @3 OF ROUTE",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM18",
        direction: Direction::Downlink,
        template: "REQUEST @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM19",
        direction: Direction::Downlink,
        template: "REQUEST @1 TO @2",
        placeholders: &[PlaceholderKind::Speed, PlaceholderKind::Speed],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM20",
        direction: Direction::Downlink,
        template: "REQUEST VOICE CONTACT",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM21",
        direction: Direction::Downlink,
        template: "REQUEST VOICE CONTACT ON @1",
        placeholders: &[PlaceholderKind::Frequency],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM22",
        direction: Direction::Downlink,
        template: "REQUEST DIRECT TO @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM23",
        direction: Direction::Downlink,
        template: "REQUEST @1",
        placeholders: &[PlaceholderKind::Procedure],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM24",
        direction: Direction::Downlink,
        template: "REQUEST @1",
        placeholders: &[PlaceholderKind::Route],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM25",
        direction: Direction::Downlink,
        template: "REQUEST CLEARANCE",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM26",
        direction: Direction::Downlink,
        template: "REQUEST WEATHER DEVIATION TO @1 VIA @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Route],
        response: ResponseRequirement::AnyRequired,
    },
    // Patched: libcpdlc's .text lacked the trailing direction placeholder; phrasing mirrors sibling UM82.
    ElementSpec {
        id: "DM27",
        direction: Direction::Downlink,
        template: "REQUEST WEATHER DEVIATION UP TO @1 @2",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM28",
        direction: Direction::Downlink,
        template: "LEAVING @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM29",
        direction: Direction::Downlink,
        template: "CLIMBING TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM30",
        direction: Direction::Downlink,
        template: "DESCENDING TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM31",
        direction: Direction::Downlink,
        template: "PASSING @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM32",
        direction: Direction::Downlink,
        template: "PASSING @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM33",
        direction: Direction::Downlink,
        template: "PRESENT POSITION @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM34",
        direction: Direction::Downlink,
        template: "PRESENT SPEED @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM35",
        direction: Direction::Downlink,
        template: "PRESENT HEADING @1",
        placeholders: &[PlaceholderKind::Degrees],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM36",
        direction: Direction::Downlink,
        template: "PRESENT GROUND TRACK @1",
        placeholders: &[PlaceholderKind::Degrees],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM37",
        direction: Direction::Downlink,
        template: "LEVEL @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM38",
        direction: Direction::Downlink,
        template: "ASSIGNED ALTITUDE @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM39",
        direction: Direction::Downlink,
        template: "ASSIGNED SPEED @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM40",
        direction: Direction::Downlink,
        template: "ASSIGNED ROUTE @1",
        placeholders: &[PlaceholderKind::Route],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM41",
        direction: Direction::Downlink,
        template: "BACK ON ROUTE",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM42",
        direction: Direction::Downlink,
        template: "NEXT WAYPOINT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM43",
        direction: Direction::Downlink,
        template: "NEXT WAYPOINT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM44",
        direction: Direction::Downlink,
        template: "ENSUING WAYPOINT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM45",
        direction: Direction::Downlink,
        template: "REPORTED WAYPOINT @1",
        placeholders: &[PlaceholderKind::Position],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM46",
        direction: Direction::Downlink,
        template: "REPORTED WAYPOINT @1",
        placeholders: &[PlaceholderKind::Time],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM47",
        direction: Direction::Downlink,
        template: "SQUAWKING @1",
        placeholders: &[PlaceholderKind::Squawk],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM48",
        direction: Direction::Downlink,
        template: "POSITION REPORT @1",
        placeholders: &[PlaceholderKind::PositionReport],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM49",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM50",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT @1 TO @2",
        placeholders: &[PlaceholderKind::Speed, PlaceholderKind::Speed],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM51",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT BACK ON ROUTE",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM52",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT LOWER ALTITUDE",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM53",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT HIGHER ALTITUDE",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM54",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT CRUISE CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM55",
        direction: Direction::Downlink,
        template: "PAN PAN PAN",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM56",
        direction: Direction::Downlink,
        template: "MAYDAY MAYDAY MAYDAY",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM57",
        direction: Direction::Downlink,
        template: "@1 OF FUEL REMAINING AND @2 PERSONS ON BOARD",
        placeholders: &[
            PlaceholderKind::TimeDuration,
            PlaceholderKind::PersonsOnBoard,
        ],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM58",
        direction: Direction::Downlink,
        template: "CANCEL EMERGENCY",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM59",
        direction: Direction::Downlink,
        template: "DIVERTING TO @1 VIA @2",
        placeholders: &[PlaceholderKind::Position, PlaceholderKind::Route],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM60",
        direction: Direction::Downlink,
        template: "OFFSETTING @1 @2 OF ROUTE",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM61",
        direction: Direction::Downlink,
        template: "DESCENDING TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM62",
        direction: Direction::Downlink,
        template: "ERROR @1",
        placeholders: &[PlaceholderKind::ErrorInfo],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM63",
        direction: Direction::Downlink,
        template: "NOT CURRENT DATA AUTHORITY",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM64",
        direction: Direction::Downlink,
        template: "@1",
        placeholders: &[PlaceholderKind::IcaoId],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM65",
        direction: Direction::Downlink,
        template: "DUE TO WEATHER",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM66",
        direction: Direction::Downlink,
        template: "DUE TO AIRCRAFT PERFORMANCE",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67",
        direction: Direction::Downlink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67b",
        direction: Direction::Downlink,
        template: "WE CAN ACCEPT @1 AT @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Time],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67c",
        direction: Direction::Downlink,
        template: "WE CAN ACCEPT @1 AT @2",
        placeholders: &[PlaceholderKind::Speed, PlaceholderKind::Time],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67d",
        direction: Direction::Downlink,
        template: "WE CAN ACCEPT @1 @2 AT @3",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
            PlaceholderKind::Time,
        ],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67e",
        direction: Direction::Downlink,
        template: "WE CANNOT ACCEPT @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67f",
        direction: Direction::Downlink,
        template: "WE CANNOT ACCEPT @1",
        placeholders: &[PlaceholderKind::Speed],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67g",
        direction: Direction::Downlink,
        template: "WE CANNOT ACCEPT @1 @2",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67h",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT CLIMB TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM67i",
        direction: Direction::Downlink,
        template: "WHEN CAN WE EXPECT DESCENT TO @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM68",
        direction: Direction::Downlink,
        template: "@1",
        placeholders: &[PlaceholderKind::FreeText],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM69",
        direction: Direction::Downlink,
        template: "REQUEST VMC DESCENT",
        placeholders: &[],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM70",
        direction: Direction::Downlink,
        template: "REQUEST HEADING @1",
        placeholders: &[PlaceholderKind::Degrees],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM71",
        direction: Direction::Downlink,
        template: "REQUEST GROUND TRACK @1",
        placeholders: &[PlaceholderKind::Degrees],
        response: ResponseRequirement::AnyRequired,
    },
    ElementSpec {
        id: "DM72",
        direction: Direction::Downlink,
        template: "REACHING @1",
        placeholders: &[PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM73",
        direction: Direction::Downlink,
        template: "@1",
        placeholders: &[PlaceholderKind::Version],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM74",
        direction: Direction::Downlink,
        template: "MAINTAIN OWN SEPARATION AND VMC",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM75",
        direction: Direction::Downlink,
        template: "AT PILOTS DISCRETION",
        placeholders: &[],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM76",
        direction: Direction::Downlink,
        template: "REACHING BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM77",
        direction: Direction::Downlink,
        template: "ASSIGNED BLOCK @1 TO @2",
        placeholders: &[PlaceholderKind::Altitude, PlaceholderKind::Altitude],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM78",
        direction: Direction::Downlink,
        template: "AT @1 @2 @3 @4",
        placeholders: &[
            PlaceholderKind::Time,
            PlaceholderKind::Distance,
            PlaceholderKind::ToFrom,
            PlaceholderKind::Position,
        ],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM79",
        direction: Direction::Downlink,
        template: "ATIS @1",
        placeholders: &[PlaceholderKind::AtisCode],
        response: ResponseRequirement::NotRequired,
    },
    ElementSpec {
        id: "DM80",
        direction: Direction::Downlink,
        template: "DEVIATING @1 @2 OF ROUTE",
        placeholders: &[
            PlaceholderKind::DistanceOffset,
            PlaceholderKind::LateralDirection,
        ],
        response: ResponseRequirement::NotRequired,
    },
];
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_duplicate_ids_within_a_table() {
        for table in [
            HOPPIE_UM_TABLE,
            GOLD_UM_TABLE,
            HOPPIE_DM_TABLE,
            GOLD_DM_TABLE,
        ] {
            let mut seen = std::collections::HashSet::new();
            for spec in table {
                assert!(seen.insert(spec.id), "duplicate element id {}", spec.id);
            }
        }
    }

    #[test]
    fn no_duplicate_ids_across_hoppie_and_gold_within_a_direction() {
        let mut seen = std::collections::HashSet::new();
        for spec in HOPPIE_UM_TABLE.iter().chain(GOLD_UM_TABLE.iter()) {
            assert!(
                seen.insert(spec.id),
                "duplicate UM id {} across Hoppie/GOLD tables",
                spec.id
            );
        }
        let mut seen = std::collections::HashSet::new();
        for spec in HOPPIE_DM_TABLE.iter().chain(GOLD_DM_TABLE.iter()) {
            assert!(
                seen.insert(spec.id),
                "duplicate DM id {} across Hoppie/GOLD tables",
                spec.id
            );
        }
    }

    #[test]
    fn every_row_direction_matches_its_table() {
        for spec in HOPPIE_UM_TABLE.iter().chain(GOLD_UM_TABLE.iter()) {
            assert_eq!(
                spec.direction,
                Direction::Uplink,
                "{} in a UM table",
                spec.id
            );
        }
        for spec in HOPPIE_DM_TABLE.iter().chain(GOLD_DM_TABLE.iter()) {
            assert_eq!(
                spec.direction,
                Direction::Downlink,
                "{} in a DM table",
                spec.id
            );
        }
    }

    #[test]
    fn every_template_placeholder_count_matches_declared_placeholders() {
        // Guards against the exact bug the "five template patches"
        // module doc describes: a template with fewer @N markers than
        // declared placeholders silently drops values on resolve().
        for spec in HOPPIE_UM_TABLE
            .iter()
            .chain(GOLD_UM_TABLE.iter())
            .chain(HOPPIE_DM_TABLE.iter())
            .chain(GOLD_DM_TABLE.iter())
        {
            let at_count = (1..=spec.placeholders.len())
                .filter(|n| spec.template.contains(&format!("@{n}")))
                .count();
            assert_eq!(
                at_count,
                spec.placeholders.len(),
                "{}: template {:?} has {} @N markers but {} placeholders declared",
                spec.id,
                spec.template,
                at_count,
                spec.placeholders.len()
            );
        }
    }

    #[test]
    fn gold_table_size_is_the_expected_order_of_magnitude() {
        // Loose sanity bound, not an exact count -- catches a
        // catastrophic extraction regression (e.g. accidentally
        // re-running against a truncated source) without being brittle
        // against a future libcpdlc update adding/removing a handful
        // of rows.
        assert!(
            GOLD_UM_TABLE.len() > 150,
            "GOLD_UM_TABLE looks truncated: {} rows",
            GOLD_UM_TABLE.len()
        );
        assert!(
            GOLD_DM_TABLE.len() > 60,
            "GOLD_DM_TABLE looks truncated: {} rows",
            GOLD_DM_TABLE.len()
        );
    }
}
